server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/C89-S3-Ply-sq
    username: root
    password: 123456
